version: '3'

services:
  api_prod:
    build:
      context: ./
      args:
        ENVIRONMENT: production
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    # Más configuraciones para producción (p. ej., volúmenes, redes, etc.)

  api_dev:
    build:
      context: ./
      args:
        ENVIRONMENT: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    # Más configuraciones para desarrollo
